### ISSUE TITLE
Error with emtpy Library

### ISSUE THREAD

**Issue by andystrobel** [wolf-box/humhub-modules-library#1]
When you install the module and click on the TopMenu entry "Library" you get an error, if you haven't created content before.

![screenshot](https://cloud.githubusercontent.com/assets/6032728/6163313/b27205e8-b290-11e4-9e15-1578829f3383.png)

**Comment by wolf-box** [comment]
Fixed in commit 85fb921bb1f69345bc2128baef859f1d77466ad7
